version: '3'

networks:
  nginx:
    name: nginx

volumes:
  nginx_proxy_manager:
    name: nginx_proxy_manager
  portainer:
    name: portainer
  
services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - nginx
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - nginx_proxy_manager:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 81:81

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: unless-stopped
    networks:
      - nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    expose:
      - 9000

