version: '3'

networks:
  monitoring:
    name: monitoring
  nginx:
    external: true
    
volumes:
  grafana:
    name: grafana
  prometheus:
    name: prometheus

services:
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    restart: unless-stopped
    networks:
      - nginx
      - monitoring
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=${GF_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD:-admin}
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    expose:
      - 3000

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
      - node_exporter
    expose:
      - 9090

  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  node_exporter:
    image: 'quay.io/prometheus/node-exporter:latest'
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - monitoring
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100

  loki:
    image: 'grafana/loki:2.5.0'
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - promtail
    volumes:
      - ./loki.yml:/etc/loki/local-config.yml
    networks:
      - monitoring
    expose:
      - 3100

  promtail:
    image: 'grafana/promtail:2.5.0'
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
    networks:
      - monitoring