version: '3'

networks:
  monitoring:
    name: monitoring
  nginx:
    external: true
    
volumes:
  prometheus:
    name: prometheus_cloud

services:
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
      - nginx
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
      - node_exporter
    expose:
      - 9090

  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  node_exporter:
    image: 'quay.io/prometheus/node-exporter:latest'
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - monitoring
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100

  promtail:
    image: 'grafana/promtail:main'
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
    networks:
      - monitoring