global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

remote_write:
  - url: https://<Prometheus url>.grafana.net/api/prom/push
    basic_auth:
      username: <username>
      password: <Your Grafana.com API Key>